In [10]:
import numpy as np
from einops import rearrange



In [53]:
a = np.random.randn(3, 3)
a

array([[-0.42999253, -0.09143155, -0.44832607],
       [ 1.63668128, -0.52507595, -1.41094546],
       [-0.06102138,  0.09207157, -1.72699121]])

In [59]:
# Create a sample 2D array
x = np.arange(12).reshape(3, 4)
print("Original array:\n", x)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
# Rearrange: flatten the array
flat = rearrange(x, 'h w -> (h w)')
print("\nFlattened array:\n", flat)



Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [61]:
# Rearrange: swap axes
swapped = rearrange(x, 'h w -> w h')
print("\nSwapped axes:\n", swapped)



Swapped axes:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [62]:
# Rearrange: split each row into two columns
split = rearrange(x, 'h (w1 w2) -> h w1 w2', w1=2)
print("\nSplit columns:\n", split)


Split columns:
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
